/*
Highlight and execute the following statement to drop the trigger
before executing the create statement.

DROP TRIGGER ART_DISC_NO_CONTROL_AFT_UPD_0;

*/

CREATE TRIGGER ART_DISC_NO_CONTROL_AFT_UPD_0 FOR ARTICULOS_DISCRETOS
AFTER UPDATE
AS 
/* TRIGGER QUE ACTUALIZA EL CAMPO NO_CONTROL DE LA TABLA DE INVENTARIOS DE ZEUS
*/
DECLARE VARIABLE UPDATED VARCHAR(1)='F';
BEGIN 
  IF (OLD.CLAVE <> NEW.CLAVE) THEN BEGIN
    --ACTUALIZAR INVENTARIOS.NO_CONTROL
--    SELECT * FROM UPDATE_INVENTARIO_ZEUS(OLD.CLAVE, NEW.CLAVE) INTO :UPDATED;
    EXECUTE PROCEDURE UPDATE_INVENTARIO_ZEUS (OLD.CLAVE, NEW.CLAVE) ;
  END
END

