CREATE OR ALTER PROCEDURE UPDATE_CLIENTES_COMPLEMENTOS RETURNS (V_CLIENTE_ID INTEGER, V_CLIENTE_MATRIZ_ID integer)
AS 
DECLARE lcComando varchar(500);
BEGIN
      
      lcComando = 'select cs.CLIENTE_ID, cs.CLIENTE_MATRIZ_ID  from CLIENTES_COMPLEMENTOS_CSV cs where cs.CLIENTE_ID is not null and cs.CLIENTE_MATRIZ_ID is not null ';
FOR EXECUTE STATEMENT lcComando
      
into :V_CLIENTE_ID, :V_CLIENTE_MATRIZ_ID      
   DO BEGIN
    update CLIENTES_COMPLEMENTOS   set CLIENTE_MATRIZ_ID = :V_CLIENTE_MATRIZ_ID, LIGADO_A_ORGANIZACION = 'S' where CLIENTE_ID = :V_CLIENTE_ID;

    SUSPEND;
   END

 END


