CREATE TABLE ERROR_LOG
(ID INTEGER NOT NULL,
FECHA TIMESTAMP NOT NULL,
USUARIO VARCHAR(25) NOT NULL,
LUGAR VARCHAR(25) NOT NULL,
NO_ERROR VARCHAR(25) NOT NULL,
DESCRIPCION VARCHAR(250),
PRIMARY KEY (ID));