
CREATE TABLE SERIES_TO_UPDATE
(ID INTEGER NOT NULL,
DESGLOSE_DISCRETO_VE_ID_OLD INTEGER default NULL,
DESGLOSE_DISCRETO_VE_ID_NEW INTEGER NOT NULL,
FECHA TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
UPDATED CHAR(1) DEFAULT 'F' NOT NULL,
PRIMARY KEY (ID));
