CREATE OR ALTER PROCEDURE UPDATE_FECHAS_SERIES_CLIENTES RETURNS (V_INVENTARIO_ID INTEGER, V_FECHA_SERIE DATE)
AS DECLARE lcComando varchar(500);
DECLARE VARIABLE V_FECHA_CLIENTE DATE;
DECLARE VARIABLE V_NO_CONTROL VARCHAR(30);
BEGIN
      
      lcComando = 'SELECT TRIM(F.NO_CONTROL), F.FECHA_SERIE, F.FECHA_CLIENTE FROM FECHAS_SERIE_CLIENTE F ORDER BY F.CLIENTE_ID';
FOR EXECUTE STATEMENT lcComando
      
into :V_NO_CONTROL, :V_FECHA_SERIE, :V_FECHA_CLIENTE
   DO BEGIN
    V_INVENTARIO_ID = (SELECT FIRST 1 I.INVENTARIO_ID FROM INVENTARIOS I WHERE I.NO_CONTROL = :V_NO_CONTROL);
    UPDATE LIBRES_INVENTARIOS SET FECHAULTSERVCLIENTE= :V_FECHA_CLIENTE, FECHAULTSERVSERIE = :V_FECHA_SERIE
    WHERE INVENTARIO_ID = :V_INVENTARIO_ID ;
    
    SUSPEND;
   END

 END

