CREATE OR ALTER PROCEDURE UPDATE_FECHAS_SERIES_CLIENTES RETURNS (V_INVENTARIO_ID INTEGER, V_FECHA_SERIE DATE)
AS DECLARE lcComando varchar(500);
DECLARE VARIABLE V_FECHA_CLIENTE DATE;
DECLARE VARIABLE V_NO_CONTROL VARCHAR(30);
declare variable v_descripcion varchar(500);
BEGIN
      
      lcComando = 'SELECT TRIM(F.NO_CONTROL), F.FECHA_SERIE, F.FECHA_CLIENTE FROM FECHAS_SERIE_CLIENTE F ORDER BY F.CLIENTE_ID';
FOR EXECUTE STATEMENT lcComando
      
into :V_NO_CONTROL, :V_FECHA_SERIE, :V_FECHA_CLIENTE
   DO BEGIN
    V_INVENTARIO_ID = (SELECT FIRST 1 I.INVENTARIO_ID FROM INVENTARIOS I WHERE I.NO_CONTROL = :V_NO_CONTROL);
    UPDATE LIBRES_INVENTARIOS SET FECHAULTSERVCLIENTE= :V_FECHA_CLIENTE, FECHAULTSERVSERIE = :V_FECHA_SERIE
    WHERE INVENTARIO_ID = :V_INVENTARIO_ID ;
    
    select trim(i.NO_CONTROL) || ' / ' ||  trim(l.MODELO_APARATO)|| ' / ' || l.FECHA_DE_VENTA || ' / ' || l.NUMERO_ULTIMA_POLIZA  
   || ' / ' || trim(coalesce(l.CONTACTO,'')) || ' / ' || trim(coalesce(l.CODIGO_CONTACTO,'')) || ' / ' || coalesce(l.FECHAULTSERVSERIE,'') || ' / ' || coalesce(l.FECHAULTSERVCLIENTE,'')
   from inventarios i inner join LIBRES_INVENTARIOS l on i.INVENTARIO_ID = l.INVENTARIO_ID where l.INVENTARIO_ID = :V_INVENTARIO_ID into :v_descripcion;
  
   update INVENTARIOS set DESCRIPCION_INTERNA = :v_descripcion where INVENTARIO_ID = :V_INVENTARIO_ID;
   v_descripcion = '';
    
    SUSPEND;
   END

 END

