CREATE TABLE CLIENTES_COMPLEMENTOS_VENDOR (
	CLIENTE_ID INTEGER DEFAULT NULL,
	NOMBRE_COMERCIAL VARCHAR(50),
	CONTACTO_ID INTEGER DEFAULT NULL,
	NOMBRE VARCHAR(50),
	VENDEDOR_ID INTEGER DEFAULT NULL
);

