CREATE OR ALTER PROCEDURE UPDATE_FECHA_ULT_SERV_CLIENTE RETURNS (V_CODIGO_CONTACTO VARCHAR(30), V_FECHA_SERIE DATE)
AS DECLARE lcComando varchar(1000);
BEGIN
      
      lcComando = 'select distinct TRIM(l.CODIGO_CONTACTO)  from INVENTARIOS i inner join LIBRES_INVENTARIOS l on l.INVENTARIO_ID=i.INVENTARIO_ID ' ||
                  ' where l.FECHAULTSERVCLIENTE is not null and l.CODIGO_CONTACTO <>' || '''' || '' || '''' || ' order by l.CODIGO_CONTACTO';
FOR EXECUTE STATEMENT lcComando      
into :V_CODIGO_CONTACTO
   DO BEGIN
    select FIRST 1 l.FECHAULTSERVCLIENTE from INVENTARIOS i inner join LIBRES_INVENTARIOS l on l.INVENTARIO_ID=i.INVENTARIO_ID where l.CODIGO_CONTACTO = :V_CODIGO_CONTACTO AND l.FECHAULTSERVCLIENTE is not null ORDER BY L.FECHAULTSERVCLIENTE DESC INTO :V_FECHA_SERIE;
    UPDATE LIBRES_INVENTARIOS L SET L.FECHAULTSERVCLIENTE = :V_FECHA_SERIE WHERE L.CODIGO_CONTACTO = :V_CODIGO_CONTACTO AND L.FECHAULTSERVCLIENTE IS NULL;
    --SELECT FIRST 1 CURRENT_DATE FROM LIBRES_INVENTARIOS L WHERE L.CODIGO_CONTACTO = :V_CODIGO_CONTACTO INTO :V_FECHA_SERIE;


    SUSPEND;
   END

 END