select * from UPD_CALIF_SERV_COBRA;


select d.CONTACTO_ID from DATOS_CALIF_SERV_COBRA d;

select l.CALIFLLAMSERCOBRA, l.FECULTSERVCOBRA from LIBRES_INVENTARIOS l where l.CODIGO_CONTACTO in (select d.CONTACTO_ID from DATOS_CALIF_SERV_COBRA d);
update LIBRES_INVENTARIOS l set l.FECULTSERVCOBRA=null, l.CALIFLLAMSERCOBRA=null where l.CODIGO_CONTACTO in (select d.CONTACTO_ID from DATOS_CALIF_SERV_COBRA d);

select i.DESCRIPCION_INTERNA from INVENTARIOS i where i.INVENTARIO_ID in (select l.INVENTARIO_ID from LIBRES_INVENTARIOS l where l.CODIGO_CONTACTO in (select d.CONTACTO_ID from DATOS_CALIF_SERV_COBRA d));
update INVENTARIOS i set i.DESCRIPCION_INTERNA = null where i.INVENTARIO_ID in (select l.INVENTARIO_ID from LIBRES_INVENTARIOS l where l.CODIGO_CONTACTO in (select d.CONTACTO_ID from DATOS_CALIF_SERV_COBRA d));


select * from INVENTARIOS_CLIENTES i;
select * from CONTACTO_CONTACTOS c where c.CONTACTO_ID=150430;
select * from INVENTARIOS i where i.CONTACTO_CREADOR_ID = 150430;
select * from LIBRES_INVENTARIOS l where l.CODIGO_CONTACTO ='150430';
select * from LIBRES_INVENTARIOS;