update 
CREATE TABLE CLIENTES_COMPLEMENTOS_CSV (
	ORDEN INTEGER,
	CLIENTE_ID INTEGER,
	GIRO_ID INTEGER,
	CALIFICACION_ID VARCHAR(25),
	ORIGEN_ID VARCHAR(25),
	CON_IMPUESTO VARCHAR(25),
	NOMBRE_COMERCIAL VARCHAR(50),
	RESPETAR_VENDEDOR VARCHAR(25),
	FECHA_ULT_ACCION VARCHAR(25),
	ULT_ACCION_TAREA_ID VARCHAR(25),
	CLIENTE_MATRIZ_ID VARCHAR(25),
	FECHA_CONVERSION VARCHAR(25),
	TIPO_ORGANIZACION_ID INTEGER,
	HABILITAR_POLITICA_PREC_ART VARCHAR(25),
	LIGADO_ORGANIZACION VARCHAR(25),
	CONTACTO_CONTACTO_ULT_ID VARCHAR(25),
	VENDEDOR_ID INTEGER
);

