INSERT INTO LIBRES_INVENTARIOS (INVENTARIO_ID, MODELO_APARATO, CONTACTO, NUMERO_ULTIMA_POLIZA, CODIGO_CONTACTO, FECHA_DE_VENTA)
SELECT TRIM(I.INVENTARIO_ID) INVENTARIO_ID
,(SELECT FIRST 1 SUBSTRING(S.MODELO FROM 1 FOR 25) FROM SERIES_APARATOS S WHERE S.SERI = I.NO_CONTROL ) MODELO
,(select first 1 trim(c.NOMBRE)  from CONTACTO_CONTACTOS c where c.CONTACTO_ID = (i.contacto_creador_id) )NOMBRE 
,(SELECT FIRST 1 TRIM(S.GARANTIA_POLIZA) POLIZA FROM SERIES_APARATOS S WHERE S.SERI = I.NO_CONTROL ) POLIZA
,(SELECT FIRST 1 id_eurowin FROM SERIES_APARATOS S WHERE S.SERI = I.NO_CONTROL ) id_eurowin
,I.VIGENCIA_INICIO
FROM INVENTARIOS I 
;


