INSERT INTO INVENTARIOS ( NO_CONTROL, CONTACTO_CREADOR_ID, DESCRIPCION_INTERNA, VIGENCIA_INICIO, VIGENCIA_FIN)
SELECT   substring(S.SERI from 1 for 30), S.ID_CLIENTE, ( substring(S.SERI from 1 for 20 ) || '/ ' ||  
substring(modelo from 1 for 20 ) || ' / ' || S.FECHA_VENTA || ' / ' || S.GARANTIA_POLIZA  || ' / ' || S.NOMBRE || ' / ' || TRIM(S.CONTACTO_ID))
,CAST((SUBSTRING(FECHA_VENTA FROM position ('/', FECHA_VENTA, position('/' IN FECHA_VENTA)+1)+1 FOR 4 ) ||'/'||
SUBSTRING(FECHA_VENTA FROM position('/' IN FECHA_VENTA)+1 FOR 2 )  ||'/'||
SUBSTRING(lpad(FECHA_VENTA, 10, '0') FROM 1 FOR 2 )) AS DATE) CAST_DESDE
,dateadd (YEAR, 1, (CAST((SUBSTRING(FECHA_VENTA FROM position ('/', FECHA_VENTA, position('/' IN FECHA_VENTA)+1)+1 FOR 4 ) ||'/'||
SUBSTRING(FECHA_VENTA FROM position('/' IN FECHA_VENTA)+1 FOR 2 )  ||'/'||
SUBSTRING(lpad(FECHA_VENTA, 10, '0') FROM 1 FOR 2 )) AS DATE)))
FROM SERIES_APARATOS S ORDER BY ID_CLIENTE;