INSERT INTO LIBRES_INVENTARIOS (INVENTARIO_ID, MODELO_APARATO, CONTACTO, NUMERO_ULTIMA_POLIZA, CODIGO_CONTACTO, FECHA_DE_VENTA)
SELECT TRIM(I.INVENTARIO_ID) INVENTARIO_ID, (SELECT FIRST 1 SUBSTRING(S.MODELO FROM 1 FOR 25) FROM SERIES_APARATOS S WHERE S.SERI = I.NO_CONTROL ) MODELO,
TRIM( C.NOMBRE) NOMBRE, (SELECT FIRST 1 TRIM(S.GARANTIA_POLIZA) POLIZA FROM SERIES_APARATOS S WHERE S.SERI = I.NO_CONTROL ) POLIZA
,TRIM(C.CONTACTO_ID) CONTACTO_ID, I.VIGENCIA_INICIO
FROM CONTACTO_CONTACTOS C INNER JOIN INVENTARIOS I ON  I.CONTACTO_CREADOR_ID = C.CONTACTO_ID ;