CREATE TABLE SERIES_APARATOS
(
  ID_EUROWIN Char(20),
  ID_CLIENTE Integer,
  NOMBRE Varchar(50),
  SERI Varchar(100),
  MODELO Varchar(100),
  FECHA_VENTA date,
  GARANTIA_POLIZA Varchar(25),
  CONTACTO Varchar(50),
  CONTACTO_ID Char(20),
  FECHA_DESDE date,
  FECHA_HASTA date,
  REFACCION Varchar(25),
  TIPO_OBJETO_DSCTO Varchar(25),
  OBJETO_DSCTO_ID Varchar(25),
  POSICION Varchar(25),
  DSCTO Varchar(25),
  MOLDES_FABRICACION Varchar(25),
  TIPO_OBJETO_DSCTO2 Varchar(25),
  OBJETO_DSCTO_ID2 Varchar(25),
  POSICION2 Varchar(25),
  DSCTO2 Varchar(25),
  LINESERVICIOS_TALLER Varchar(25),
  TIPO_OBJETO_DSCTO3 Varchar(25),
  OBJETO_DSCTO_ID3 Varchar(25),
  POSICION3 Varchar(25),
  DSCTO3 Varchar(25)
);

GRANT DELETE, INSERT, REFERENCES, SELECT, UPDATE
 ON SERIES_APARATOS TO  SYSDBA WITH GRANT OPTION;

select * from SERIES_APARATOS;
select * from POLITICAS_DSCTOS;
DROP TABLE SERIES_APARATOS;