INSERT INTO LIBRES_INVENTARIOS (INVENTARIO_ID, MODELO_APARATO, CONTACTO, NUMERO_ULTIMA_POLIZA, CODIGO_CONTACTO, FECHA_DE_VENTA)
SELECT I.INVENTARIO_ID, replace(TRIM(S.MODELO),'Ê',''), 
replace(replace(replace(REPLACE(TRIM(S.NOMBRE_CLIENTE ),'„','Ñ'),'’','í'),'‡','á'),'—','ó'), 
'Garantía', S.CLIENTE_ID_MICROSIP ,
 cast(S.FECHA_VENTA  as date )
FROM INVENTARIOS I inner join SERIES_VENDIDOS_PRI_TODOS  S ON S.NO_SERIE =I.NO_CONTROL
;

