insert into POLITICAS_DSCTOS
select 'INV' tipo_objeto, i.INVENTARIO_ID, t.OBJETO_DSCTO, t.OBJETO_DSCTO_ID,  t.POSICION, t.DSCTO
from SERIES_VENDIDOS_PRI_TODOS t inner join INVENTARIOS i on i.NO_CONTROL = t.NO_SERIE;
;

insert into POLITICAS_DSCTOS
select 'INV' tipo_objeto, i.INVENTARIO_ID, t.TIPO_OBJETO_DSCTO2, t.OBJETO_DSCTO_ID2,  t.POSICION2, t.DSCTO2
from SERIES_VENDIDOS_PRI_TODOS t inner join INVENTARIOS i on i.NO_CONTROL = t.NO_SERIE;
;

insert into POLITICAS_DSCTOS
select 'INV' tipo_objeto, i.INVENTARIO_ID, t.OBJETO_DSCTO3, t.OBJETO_DSCTO_ID3,  t.POSICION3, t.DSCTO3
from SERIES_VENDIDOS_PRI_TODOS t inner join INVENTARIOS i on i.NO_CONTROL = t.NO_SERIE;
;

select count(*) from POLITICAS_DSCTOS;